version: "3"

services:
  app:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: micro-auth-app
    volumes:
      - ./frontend/build/catalog-admin:/opt/jboss/keycloak/themes/catalog-admin
      - ./keycloak/config/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      - ./keycloak/test-realm-export.json:/tmp/test-realm-export.json
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/test-realm-export.json
      - DB_ADDR=db
      - DB_VENDOR=POSTGRES
      - DB_SCHEMA=public
      - DB_DATABASE=micro_auth
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - db
    networks: 
      default:
        aliases: 
          - app.test

  db:
    image: postgres
    container_name: micro-auth-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=micro_auth
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - default

  frontend:
    build: ./frontend
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-frontend
    volumes:
      - ./frontend:/home/node/app
    networks: 
      - default

  test:
    build: ./tests
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test
    volumes:
      - ./tests:/home/node/app
    networks: 
      - default

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    networks: 
      - default

networks: 
  default:
    driver: bridge